version: '3'
services:
  registration-db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=airlineradmin
      - POSTGRES_PASSWORD=testeventstreammonitor#123
      - POSTGRES_DB=REGISTRATIONS
    ports:
      - "3304:5432"

  registration-service:
#    build:
#      context: /Users/kamalsaidevarapalli/Desktop/Workshop/AirlinerAdminstration
#      dockerfile: /Users/kamalsaidevarapalli/Desktop/Workshop/AirlinerAdminstration/Dockerfile.reg
    image: registrations:v1
    ports:
      - "5001:9091"
    depends_on:
      - registration-db
    env_file:
      - /Users/kamalsaidevarapalli/Desktop/Workshop/AirlinerAdminstration/src/registration_service/.env.prod

