apiVersion: apps/v1
kind: Deployment
metadata:
  name: miniapp-authtokendb
  namespace: miniapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authtoken-dbapp
  template:
    metadata:
      labels:
        app: authtoken-dbapp
    spec:
      containers:
        - name: postgres-db-token-app
          image: postgres:latest
          env:
            - name: POSTGRES_USER
              value: airlineradmin
            - name: POSTGRES_PASSWORD
              value: testeventstreammonitor#123
            - name: POSTGRES_DB
              value: AUTHTOKENS
          ports:
            - containerPort: 5432
