apiVersion: apps/v1
kind: Deployment
metadata:
  name: authtokens-db-deployment
  namespace: miniapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authtokens-db
  template:
    metadata:
      labels:
        app: authtokens-db
    spec:
      containers:
        - name: postgres-db-token-app
          image: postgres:latest
          env:
            - name: POSTGRES_USER
              value: airlineradmin
            - name: POSTGRES_PASSWORD
              value: testeventstreammonitor#123
            - name: POSTGRES_DB
              value: AUTHTOKENS
          ports:
            - containerPort: 5432
